version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: backend.Dockerfile  
    command: bash -c "dockerize -wait tcp://db:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./openrazor_backend:/app/openrazor_backend  

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./openrazor_frontend:/app/openrazor_frontend